export const SET_TRAIN_LIST_DATA = 'SET_TRAIN_LIST_DATA';
export const SET_CLASS_LIST = 'SET_CLASS_LIST';
export const SET_QUESTION_DATA = 'SET_QUESTION_DATA';
export const SET_TEST_DESC_DATA = 'SET_TEST_DESC_DATA';
export const SET_REFRESH_DATA = 'SET_REFRESH_DATA';